version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.9.1-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-deps-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  test:
    jobs:
      - build
