version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.9.1-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache
          key: v1-deps-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint

      # - run:
      #     name: Build
      #     command: yarn build

      # Save public repo to a shared workspace
      # This way can be used in future tests
      # - persist_to_workspace:
      #     root: ~/repo
      #     paths:
      #       - .next


workflows:
  version: 2
  test:
    jobs:
      - build:
